services:
  whale-users-postgres:
    image: postgres:12-alpine
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    env_file:
      - .env
    ports:
      - "5432:5432"
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_SOURCE=${DB_SOURCE_DOCKER}
    env_file:
      - .env
    depends_on:
      - whale-users-postgres
    entrypoint: ["/app/wait-for.sh", "whale-users-postgres:5432", "--", "/app/start.sh"]
    command: ["/app/main"]


