// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type User struct {
	ID         uuid.UUID    `json:"id"`
	UserName   string       `json:"user_name"`
	Email      string       `json:"email"`
	Password   string       `json:"password"`
	CreatedAt  time.Time    `json:"created_at"`
	UpdatedAt  time.Time    `json:"updated_at"`
	VerifiedAt sql.NullTime `json:"verified_at"`
}

type UserProfile struct {
	ID            uuid.UUID      `json:"id"`
	UserID        uuid.UUID      `json:"user_id"`
	FirstName     sql.NullString `json:"first_name"`
	LastName      sql.NullString `json:"last_name"`
	BusinessName  sql.NullString `json:"business_name"`
	StreetAddress sql.NullString `json:"street_address"`
	City          sql.NullString `json:"city"`
	State         sql.NullString `json:"state"`
	Zip           sql.NullString `json:"zip"`
	CountryCode   sql.NullInt32  `json:"country_code"`
	CreatedAt     time.Time      `json:"created_at"`
	UpdatedAt     time.Time      `json:"updated_at"`
	VerifiedAt    sql.NullTime   `json:"verified_at"`
}

type UserRole struct {
	ID         uuid.UUID    `json:"id"`
	UserID     uuid.UUID    `json:"user_id"`
	RoleID     int32        `json:"role_id"`
	CreatedAt  time.Time    `json:"created_at"`
	UpdatedAt  time.Time    `json:"updated_at"`
	VerifiedAt sql.NullTime `json:"verified_at"`
}
