// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type User struct {
	ID         uuid.UUID    `json:"id"`
	UserName   string       `json:"user_name"`
	Email      string       `json:"email"`
	Password   string       `json:"password"`
	CreatedAt  time.Time    `json:"created_at"`
	UpdatedAt  time.Time    `json:"updated_at"`
	VerifiedAt sql.NullTime `json:"verified_at"`
}

type UserProfile struct {
	ID            uuid.UUID    `json:"id"`
	UserID        uuid.UUID    `json:"user_id"`
	FirstName     string       `json:"first_name"`
	LastName      string       `json:"last_name"`
	BusinessName  string       `json:"business_name"`
	StreetAddress string       `json:"street_address"`
	City          string       `json:"city"`
	State         string       `json:"state"`
	Zip           string       `json:"zip"`
	CountryCode   string       `json:"country_code"`
	CreatedAt     time.Time    `json:"created_at"`
	UpdatedAt     time.Time    `json:"updated_at"`
	VerifiedAt    sql.NullTime `json:"verified_at"`
}

type UserRole struct {
	ID         uuid.UUID    `json:"id"`
	UserID     uuid.UUID    `json:"user_id"`
	RoleID     int32        `json:"role_id"`
	CreatedAt  time.Time    `json:"created_at"`
	UpdatedAt  time.Time    `json:"updated_at"`
	VerifiedAt sql.NullTime `json:"verified_at"`
}
