name: ci-test

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "master" ]

jobs:

  test:
    name: Test Whale Wake
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'

      - name: Create .env file
        run: |
          echo "DB_USER=${{ secrets.DB_USER }}" >> .env
          echo "DB_PWORD=${{ secrets.DB_PWORD }}" >> .env

      - name: Test
        run: make test
