name: ci-test

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "master" ]

jobs:

  test:
    name: Test Whale Wake
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:12-alpine
        env:
          POSTGRES_USER: testuser
          POSTGRES_PASSWORD: testpassword
          POSTGRES_DB: whale_wake_users
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'

     - name: Create test .env file
       run: |
         echo "DB_USER=testuser" >> .env
         echo "DB_PWORD=testpassword" >> .env

      - name: Run Migrations
        run: make testmigrateup

      - name: Test
        run: make test
