name: ci-test

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test:
    name: Test Whale Wake
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:12-alpine
        env:
          POSTGRES_USER: testuser
          POSTGRES_PASSWORD: testpassword
          POSTGRES_DB: whale_wake_users
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24.6'

      - name: Create test .env file
        run: |
          echo "DB_DRIVER=postgres" >> .env
          echo "DB_SOURCE=postgresql://testuser:testpassword@localhost:5432/whale_wake_users?sslmode=disable" >> .env
          echo "SERVER_ADDRESS=0.0.0.0:8080" >> .env
          echo "TOKEN_SYMMETRIC_KEY=4ce9a925ba6ba4563f18113a455047f22ed914610d242f99439419aaa9d3d069" >> .env
          echo "ACCESS_TOKEN_DURATION=15m" >> .env


      - name: Install golang-migrate CLI
        run: |
          curl -L https://github.com/golang-migrate/migrate/releases/download/v4.16.2/migrate.linux-amd64.tar.gz | tar xvz
          sudo mv migrate /usr/local/bin/
          which migrate

      - name: Run Migrations
        run: make testmigrateup

      - name: Test
        run: make test